version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monitoring_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: ./API
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_LOCATION: LOCAL  # Or CLOUD depending on your setup

  datacollector:
    build: ./DataCollection
    depends_on:
      - api
    networks:
      - app-network

  renderer:
    build: ./Renderer
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
